-- require("config.lazy")
require("f0ur3y3s.settings")
require("f0ur3y3s.lazy")
-- vim.cmd("set number")
-- vim.cmd("set relativenumber")
-- vim.cmd("set hidden")
-- vim.cmd("set nobackup")
-- vim.cmd("set noswapfile")
-- vim.cmd("set nowritebackup")
-- vim.cmd("set expandtab")
-- vim.cmd("set tabstop=5")
-- vim.cmd("set shiftwidth=4")
-- vim.cmd("nnoremap <Tab> >>")
-- vim.cmd("nnoremap <S-Tab> <<")
-- vim.cmd("inoremap <S-Tab> <C-d>")
-- vim.cmd("inoremap jk <c-c>")

